jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python FT251006_Assignment2.py
